### ISSUE TITLE
À propos - Responsive portable

### ISSUE THREAD

**Issue by BlueEel** [WildCodeSchool/2023-03-remote-fr-php-afac-974#136]
Coucou 
Essayez peut-être de grossir un peu le rectangle rouge de la page à propos, toute votre page est sympa et bien agencée, c'est dommage qu'il y ait ce rectangle rouge assez fin au début !

**Comment by Karabuff** [comment]
En effet merci pour le retour.
Ca va être corrigé dans une PR futur :)
