### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by jfm-wcs** [WildCodeSchool/2023-03-remote-fr-php-afac-974#142]
Le bouton `ajout catégorie` de la page https://afac-974.remote-fr-1.wilders.dev/admin/category/ ne semble pas mener au bon endroit.
Idem à la page https://afac-974.remote-fr-1.wilders.dev/admin/painting/

**Comment by Karabuff** [comment]
L'issue est en cours de résolution dans la PR de victoria nommé "Lien favoris"...
